language: perl
perl:
- '5.18'
- '5.20'
matrix:
  fast_finish: true
install:
- cpanm --quiet --notest --skip-satisfied Dist::Zilla
- dzil authordeps          --missing | grep -vP '[^\w:]' | xargs -n 2 -P 4 cpanm
  --quiet --notest
- dzil listdeps   --author --missing | grep -vP '[^\w:]' | xargs -n 2 -P 4 cpanm
  --quiet --notest
- git clone https://github.com/dwburke/perl-Array-FIFO.git
script:
- dzil authordeps          --missing | grep -vP '[^\w:]' | xargs -n 2 -P 4 cpanm --quiet --notest
- dzil listdeps   --author --missing | grep -vP '[^\w:]' | xargs -n 2 -P 4 cpanm --quiet --notest
- dzil smoke --release --author
sudo: false

